SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE `pcms_alias` CHANGE COLUMN `accountId` `accountId` int(11) NOT NULL after `id`;
ALTER TABLE `pcms_alias` ADD COLUMN `languageId` int(11) NOT NULL DEFAULT '0' after `accountId`;
ALTER TABLE `pcms_alias` ADD COLUMN `cascade` tinyint(1) NOT NULL DEFAULT '0' after `languageId`;
ALTER TABLE `pcms_alias` CHANGE COLUMN `alias` `alias` varchar(250) NOT NULL after `cascade`;
ALTER TABLE `pcms_alias` CHANGE COLUMN `url` `url` varchar(250) NOT NULL after `alias`;
ALTER TABLE `pcms_alias` CHANGE COLUMN `active` `active` int(11) NOT NULL after `url`;
ALTER TABLE `pcms_alias` CHANGE COLUMN `sort` `sort` bigint(20) NOT NULL after `active`;
ALTER TABLE `pcms_alias` ENGINE=`InnoDB` AUTO_INCREMENT=5640 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_announce_message` CHANGE COLUMN `language` `language` varchar(100) NOT NULL after `id`;
ALTER TABLE `pcms_announce_message` CHANGE COLUMN `header` `header` varchar(150) NOT NULL after `language`;
ALTER TABLE `pcms_announce_message` ENGINE=`InnoDB` AUTO_INCREMENT=1 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_announce_user` ENGINE=`InnoDB` AUTO_INCREMENT=1 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_announce_user` ADD CONSTRAINT `pcms_announce_user_ibfk_3` FOREIGN KEY (`messageId`) REFERENCES `punchcms_nl`.`pcms_announce_message` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_audit_log` CHANGE COLUMN `accountId` `accountId` int(11) NOT NULL after `id`;
ALTER TABLE `pcms_audit_log` CHANGE COLUMN `type` `type` int(11) NOT NULL after `accountId`;
ALTER TABLE `pcms_audit_log` CHANGE COLUMN `typeId` `typeId` bigint(20) NOT NULL after `type`;
ALTER TABLE `pcms_audit_log` CHANGE COLUMN `typeName` `typeName` varchar(255) NOT NULL after `typeId`;
ALTER TABLE `pcms_audit_log` CHANGE COLUMN `userId` `userId` int(11) NOT NULL after `typeName`;
ALTER TABLE `pcms_audit_log` CHANGE COLUMN `userName` `userName` varchar(255) NOT NULL after `userId`;
ALTER TABLE `pcms_audit_log` CHANGE COLUMN `action` `action` varchar(64) NOT NULL after `userName`;
ALTER TABLE `pcms_audit_log` CHANGE COLUMN `description` `description` varchar(255) NOT NULL after `action`;
ALTER TABLE `pcms_audit_log` ENGINE=`InnoDB` AUTO_INCREMENT=64274 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_element` ENGINE=`InnoDB` AUTO_INCREMENT=40166 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_element` ADD CONSTRAINT `pcms_element_ibfk_3` FOREIGN KEY (`accountId`) REFERENCES `punchcms_nl`.`punch_account` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_element_feed` ADD COLUMN `aliasField` varchar(250) NOT NULL after `sortBy`;
ALTER TABLE `pcms_element_field` ENGINE=`InnoDB` AUTO_INCREMENT=149159 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_element_field` ADD CONSTRAINT `pcms_element_field_ibfk_1` FOREIGN KEY (`elementId`) REFERENCES `punchcms_nl`.`pcms_element` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_element_field` ADD CONSTRAINT `pcms_element_field_ibfk_2` FOREIGN KEY (`templateFieldId`) REFERENCES `punchcms_nl`.`pcms_template_field` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_element_field_bigtext` CHANGE COLUMN `languageId` `languageId` int(11) NOT NULL after `fieldId`;
ALTER TABLE `pcms_element_field_bigtext` ENGINE=`InnoDB` AUTO_INCREMENT=71932 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_element_field_bigtext` ADD CONSTRAINT `pcms_element_field_bigtext_ibfk_1` FOREIGN KEY (`fieldId`) REFERENCES `punchcms_nl`.`pcms_element_field` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_element_field_date` CHANGE COLUMN `languageId` `languageId` int(11) NOT NULL after `fieldId`;
ALTER TABLE `pcms_element_field_date` ENGINE=`InnoDB` AUTO_INCREMENT=684 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_element_field_date` ADD CONSTRAINT `pcms_element_field_date_ibfk_1` FOREIGN KEY (`fieldId`) REFERENCES `punchcms_nl`.`pcms_element_field` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_element_field_number` CHANGE COLUMN `languageId` `languageId` int(11) NOT NULL after `fieldId`;
ALTER TABLE `pcms_element_field_number` ENGINE=`InnoDB` AUTO_INCREMENT=31825 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_element_field_number` ADD CONSTRAINT `pcms_element_field_number_ibfk_1` FOREIGN KEY (`fieldId`) REFERENCES `punchcms_nl`.`pcms_element_field` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_element_field_text` CHANGE COLUMN `languageId` `languageId` int(11) NOT NULL after `fieldId`;
ALTER TABLE `pcms_element_field_text` ENGINE=`InnoDB` AUTO_INCREMENT=179209 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_element_field_text` ADD CONSTRAINT `pcms_element_field_text_ibfk_1` FOREIGN KEY (`fieldId`) REFERENCES `punchcms_nl`.`pcms_element_field` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_element_language` CHANGE COLUMN `elementId` `elementId` bigint(20) NOT NULL after `id`;
ALTER TABLE `pcms_element_language` CHANGE COLUMN `languageId` `languageId` int(11) NOT NULL after `elementId`;
ALTER TABLE `pcms_element_language` ENGINE=`InnoDB` AUTO_INCREMENT=82756 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_element_language` ADD INDEX `languageId` USING BTREE (languageId);
ALTER TABLE `pcms_element_language` ADD CONSTRAINT `pcms_element_language_ibfk_1` FOREIGN KEY (`elementId`) REFERENCES `punchcms_nl`.`pcms_element` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_element_language` ADD CONSTRAINT `pcms_element_language_ibfk_2` FOREIGN KEY (`languageId`) REFERENCES `punchcms_nl`.`pcms_language` (`id`)  ON DELETE CASCADE;
CREATE TABLE `pcms_element_meta` (
	`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`elementId` bigint(20) NOT NULL,
	`name` varchar(64) NOT NULL,
	`value` varchar(255) NOT NULL,
	`languageId` int(11) NOT NULL,
	`cascade` int(11) NOT NULL DEFAULT '0',
	`sort` int(11) NOT NULL DEFAULT '0',
	`created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	INDEX `elementId` USING BTREE (elementId),
	INDEX `languageId` USING BTREE (languageId),
	CONSTRAINT `pcms_element_meta_ibfk_1` FOREIGN KEY (`languageId`) REFERENCES `pcms_language` (`id`)  ON DELETE CASCADE,
	CONSTRAINT `pcms_element_meta_ibfk_2` FOREIGN KEY (`elementId`) REFERENCES `pcms_element` (`id`)  ON DELETE CASCADE) ENGINE=`InnoDB` AUTO_INCREMENT=5476 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_element_permission` ENGINE=`InnoDB` AUTO_INCREMENT=1 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_element_permission` ADD CONSTRAINT `pcms_element_permission_ibfk_1` FOREIGN KEY (`elementId`) REFERENCES `punchcms_nl`.`pcms_element` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_element_schedule` CHANGE COLUMN `elementId` `elementId` bigint(20) NOT NULL after `id`;
ALTER TABLE `pcms_element_schedule` ENGINE=`InnoDB` AUTO_INCREMENT=44182 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_element_schedule` ADD CONSTRAINT `pcms_element_schedule_ibfk_1` FOREIGN KEY (`elementId`) REFERENCES `punchcms_nl`.`pcms_element` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_element_type` ENGINE=`InnoDB` AUTO_INCREMENT=6 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_form` ENGINE=`InnoDB` AUTO_INCREMENT=1 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_form` ADD CONSTRAINT `pcms_form_ibfk_1` FOREIGN KEY (`accountId`) REFERENCES `punchcms_nl`.`punch_account` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_language` CHANGE COLUMN `accountId` `accountId` int(11) NOT NULL after `id`;
ALTER TABLE `pcms_language` CHANGE COLUMN `name` `name` varchar(150) NOT NULL after `accountId`;
ALTER TABLE `pcms_language` CHANGE COLUMN `abbr` `abbr` varchar(100) NOT NULL after `name`;
ALTER TABLE `pcms_language` CHANGE COLUMN `username` `username` varchar(250) NOT NULL after `sort`;
ALTER TABLE `pcms_language` ENGINE=`InnoDB` AUTO_INCREMENT=185 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_language` ADD CONSTRAINT `pcms_language_ibfk_1` FOREIGN KEY (`accountId`) REFERENCES `punchcms_nl`.`punch_account` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_search_index` CHANGE COLUMN `sort` `sort` int(11) NOT NULL after `count`;
ALTER TABLE `pcms_search_index` ENGINE=`InnoDB` AUTO_INCREMENT=634377 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_search_index` ADD CONSTRAINT `pcms_search_index_ibfk_1` FOREIGN KEY (`elementId`) REFERENCES `punchcms_nl`.`pcms_element` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_setting` ENGINE=`InnoDB` AUTO_INCREMENT=2588 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_setting` ADD CONSTRAINT `pcms_setting_ibfk_1` FOREIGN KEY (`accountId`) REFERENCES `punchcms_nl`.`punch_account` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_setting` ADD CONSTRAINT `pcms_setting_ibfk_2` FOREIGN KEY (`settingId`) REFERENCES `punchcms_nl`.`pcms_setting_tpl` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_setting_tpl` CHANGE COLUMN `section` `section` varchar(128) NOT NULL after `value`;
ALTER TABLE `pcms_setting_tpl` CHANGE COLUMN `type` `type` varchar(128) NOT NULL after `section`;
ALTER TABLE `pcms_setting_tpl` ENGINE=`InnoDB` AUTO_INCREMENT=18 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_storage_data` CHANGE COLUMN `itemId` `itemId` bigint(20) NOT NULL after `id`;
ALTER TABLE `pcms_storage_data` CHANGE COLUMN `originalName` `originalName` varchar(255) NOT NULL after `itemId`;
ALTER TABLE `pcms_storage_data` CHANGE COLUMN `localName` `localName` varchar(255) NOT NULL after `originalName`;
ALTER TABLE `pcms_storage_data` ENGINE=`InnoDB` AUTO_INCREMENT=3338 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_storage_data` ADD CONSTRAINT `pcms_storage_data_ibfk_1` FOREIGN KEY (`itemId`) REFERENCES `punchcms_nl`.`pcms_storage_item` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_storage_item` CHANGE COLUMN `accountId` `accountId` int(11) NOT NULL after `id`;
ALTER TABLE `pcms_storage_item` CHANGE COLUMN `parentId` `parentId` bigint(20) NOT NULL after `accountId`;
ALTER TABLE `pcms_storage_item` CHANGE COLUMN `name` `name` varchar(128) NOT NULL after `parentId`;
ALTER TABLE `pcms_storage_item` CHANGE COLUMN `description` `description` varchar(250) NOT NULL after `name`;
ALTER TABLE `pcms_storage_item` CHANGE COLUMN `typeId` `typeId` varchar(128) NOT NULL after `description`;
ALTER TABLE `pcms_storage_item` CHANGE COLUMN `username` `username` varchar(250) NOT NULL after `typeId`;
ALTER TABLE `pcms_storage_item` CHANGE COLUMN `sort` `sort` int(11) NOT NULL after `username`;
ALTER TABLE `pcms_storage_item` ENGINE=`InnoDB` AUTO_INCREMENT=3545 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_storage_item` ADD CONSTRAINT `pcms_storage_item_ibfk_1` FOREIGN KEY (`accountId`) REFERENCES `punchcms_nl`.`punch_account` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_storage_type` CHANGE COLUMN `name` `name` varchar(128) NOT NULL after `id`;
ALTER TABLE `pcms_storage_type` ENGINE=`InnoDB` AUTO_INCREMENT=3 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_structure` CHANGE COLUMN `fileName` `fileName` varchar(255) NOT NULL after `id`;
ALTER TABLE `pcms_structure` CHANGE COLUMN `section` `section` varchar(128) NOT NULL after `fileName`;
ALTER TABLE `pcms_structure` CHANGE COLUMN `sort` `sort` int(11) NOT NULL after `section`;
ALTER TABLE `pcms_structure` ENGINE=`InnoDB` AUTO_INCREMENT=6 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_structure_meta` CHANGE COLUMN `structureId` `structureId` int(11) NOT NULL after `id`;
ALTER TABLE `pcms_structure_meta` CHANGE COLUMN `language` `language` varchar(32) NOT NULL after `structureId`;
ALTER TABLE `pcms_structure_meta` CHANGE COLUMN `name` `name` varchar(255) NOT NULL after `language`;
ALTER TABLE `pcms_structure_meta` CHANGE COLUMN `description` `description` varchar(255) NOT NULL after `name`;
ALTER TABLE `pcms_structure_meta` CHANGE COLUMN `sort` `sort` int(11) NOT NULL after `description`;
ALTER TABLE `pcms_structure_meta` ENGINE=`InnoDB` AUTO_INCREMENT=11 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_template` ENGINE=`InnoDB` AUTO_INCREMENT=5849 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_template` ADD CONSTRAINT `pcms_template_ibfk_1` FOREIGN KEY (`accountId`) REFERENCES `punchcms_nl`.`punch_account` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_template_field` ENGINE=`InnoDB` AUTO_INCREMENT=22777 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_template_field` ADD CONSTRAINT `pcms_template_field_ibfk_1` FOREIGN KEY (`templateId`) REFERENCES `punchcms_nl`.`pcms_template` (`id`)  ON DELETE CASCADE;
ALTER TABLE `pcms_template_field_type` ENGINE=`InnoDB` AUTO_INCREMENT=16 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_template_field_value` ENGINE=`InnoDB` AUTO_INCREMENT=51481 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `pcms_template_field_value` ADD CONSTRAINT `pcms_template_field_value_ibfk_1` FOREIGN KEY (`fieldId`) REFERENCES `punchcms_nl`.`pcms_template_field` (`id`)  ON DELETE CASCADE;
ALTER TABLE `punch_account` CHANGE COLUMN `punchId` `punchId` varchar(64) NOT NULL after `id`;
ALTER TABLE `punch_account` ENGINE=`InnoDB` AUTO_INCREMENT=103 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_account_product` CHANGE COLUMN `accountId` `accountId` int(11) NOT NULL after `id`;
ALTER TABLE `punch_account_product` CHANGE COLUMN `productId` `productId` int(11) NOT NULL after `accountId`;
ALTER TABLE `punch_account_product` CHANGE COLUMN `sort` `sort` int(11) NOT NULL after `expires`;
ALTER TABLE `punch_account_product` ENGINE=`InnoDB` AUTO_INCREMENT=120 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_account_product` ADD CONSTRAINT `punch_account_product_ibfk_1` FOREIGN KEY (`accountId`) REFERENCES `punchcms_nl`.`punch_account` (`id`)  ON DELETE CASCADE;
ALTER TABLE `punch_account_product` ADD CONSTRAINT `punch_account_product_ibfk_2` FOREIGN KEY (`productId`) REFERENCES `punchcms_nl`.`punch_product` (`id`)  ON DELETE CASCADE;
ALTER TABLE `punch_liveuser_applications` ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_applications_seq` ENGINE=`InnoDB` AUTO_INCREMENT=81 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_area_admin_areas` ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_areas` ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_areas_seq` ENGINE=`InnoDB` AUTO_INCREMENT=186 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_group_subgroups` ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_grouprights` ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_groups` ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_groups_seq` ENGINE=`InnoDB` AUTO_INCREMENT=44 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_groupusers` ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_perm_users` ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_perm_users_seq` ENGINE=`InnoDB` AUTO_INCREMENT=3290 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_right_implied` ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_rights` ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_rights_seq` ENGINE=`InnoDB` AUTO_INCREMENT=190 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_translations` ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_translations_seq` ENGINE=`InnoDB` AUTO_INCREMENT=1 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_userrights` ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_users` CHANGE COLUMN `handle` `handle` char(250) DEFAULT NULL after `authuserid`;
ALTER TABLE `punch_liveuser_users` CHANGE COLUMN `time_zone_id` `time_zone_id` int(11) NOT NULL DEFAULT '1' after `email`;
ALTER TABLE `punch_liveuser_users` ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_liveuser_users_seq` ENGINE=`InnoDB` AUTO_INCREMENT=2217 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_product` CHANGE COLUMN `name` `name` varchar(150) NOT NULL after `parentId`;
ALTER TABLE `punch_product` ENGINE=`InnoDB` AUTO_INCREMENT=2 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `punch_timezone` ENGINE=`InnoDB` AUTO_INCREMENT=143 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
SET FOREIGN_KEY_CHECKS = 1;