<?php

$_CONF['app']['navRights']			= array(
										NAV_MYPUNCH_PCMS => MYPUNCH_PUNCHCMS_VIEW,
										NAV_PCMS_ELEMENTS => PUNCHCMS_ELEMENTS_VIEW,
										NAV_PCMS_TEMPLATES => PUNCHCMS_TEMPLATES_VIEW,
										NAV_PCMS_STORAGE => PUNCHCMS_STORAGE_VIEW,
										NAV_PCMS_ALIASES => PUNCHCMS_ALIASES_VIEW,
										NAV_PCMS_FEEDS => PUNCHCMS_FEEDS_VIEW,
										NAV_PCMS_LANGUAGES => PUNCHCMS_LANGUAGES_VIEW,
										NAV_PCMS_SETTINGS => PUNCHCMS_SETTINGS_VIEW,
										NAV_PCMS_SEARCH => PUNCHCMS_SEARCH_VIEW,
										NAV_PCMS_HELP => PUNCHCMS_HELP_VIEW,
										NAV_MYPUNCH_ANNOUNCEMENTS => MYPUNCH_ANNOUNCEMENTS_VIEW,
										NAV_MYPUNCH_ACCOUNT => MYPUNCH_ACCOUNT_VIEW,
										NAV_MYPUNCH_PROFILE => MYPUNCH_PROFILE_VIEW,
										NAV_MYPUNCH_USERS => MYPUNCH_USERS_VIEW,
										NAV_MYPUNCH_USERS_USER => MYPUNCH_USERS_VIEW,
										NAV_MYPUNCH_USERS_GROUP => MYPUNCH_USERS_VIEW,
										NAV_MYPUNCH_USERS_APPLICATION => MYPUNCH_USERS_VIEW,
										NAV_MYPUNCH_USERS_AREA => MYPUNCH_USERS_VIEW,
										NAV_MYPUNCH_USERS_RIGHT => MYPUNCH_USERS_VIEW
									);

?>