<?php

$_CONF['app']['navRights']			= array(
										NAV_MYPUNCH_PCMS => MYSPIN_SPINCMS_VIEW,
										NAV_PCMS_ELEMENTS => SPINCMS_ELEMENTS_VIEW,
										NAV_PCMS_TEMPLATES => SPINCMS_TEMPLATES_VIEW,
										NAV_PCMS_STORAGE => SPINCMS_STORAGE_VIEW,
										NAV_PCMS_ALIASES => SPINCMS_ALIASES_VIEW,
										NAV_PCMS_LANGUAGES => SPINCMS_LANGUAGES_VIEW,
										NAV_PCMS_SETTINGS => SPINCMS_SETTINGS_VIEW,
										NAV_PCMS_SEARCH => SPINCMS_SEARCH_VIEW,
										NAV_PCMS_HELP => SPINCMS_HELP_VIEW,
										NAV_MYPUNCH_ANNOUNCEMENTS => MYSPIN_ANNOUNCEMENTS_VIEW,
										NAV_MYPUNCH_ACCOUNT => MYSPIN_ACCOUNT_VIEW,
										NAV_MYPUNCH_PROFILE => MYSPIN_PROFILE_VIEW,
										NAV_MYPUNCH_USERS => MYSPIN_USERS_VIEW,
										NAV_MYPUNCH_USERS_USER => MYSPIN_USERS_VIEW,
										NAV_MYPUNCH_USERS_GROUP => MYSPIN_USERS_VIEW,
										NAV_MYPUNCH_USERS_APPLICATION => MYSPIN_USERS_VIEW,
										NAV_MYPUNCH_USERS_AREA => MYSPIN_USERS_VIEW,
										NAV_MYPUNCH_USERS_RIGHT => MYSPIN_USERS_VIEW
									);

?>